version : "3"
services :    
  db-postgresql:
    image: postgres:latest
    command: postgres -c 'max_connections=600'
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.5GB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhadebackend
      PGDATA: /data/postgres 
    volumes:
       - postgres-local-volume:/var/lib/postgresql-local/data                  
    expose:
      - 5432       

volumes:
    postgres-local-volume:

networks:
  default:
    name: postgre-service_default          
