version : "3"
services :    
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=600'
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.5GB'    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhadebackend
      PGDATA: /data/postgres 
    volumes:
       - postgres-local-volume:/var/lib/postgresql-local/data                  
    expose:
      - 5432   

  rinhadebackend_1:
    container_name: rinhadebackend_1
    image: docker.io/library/rinhadevbackend:0.0.1-SNAPSHOT
    environment:      
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinhadebackend
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres      
    depends_on:
      - db
    ports:
      - 8080:8080      
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.25GB'                

volumes:
    postgres-local-volume:

networks:
  default:
    name: postgre-service_default          
